### ISSUE TITLE
Empty Dependency for Litellm Environment

### ISSUE THREAD

**Issue by KOU-199024** [RenzeLou/AAAR-1.0#1]
Hi authors,

Thanks a lot for your works, and I'm trying to use this benchmark in my recent project.
However, I found that the there are no dependencies in the environment.litellm.yml file, which resulted in a failure to run the corresponding experiments on my local machine. Could you please help check if this is correct? Or did I miss something?

<img width="670" alt="image" src="https://github.com/user-attachments/assets/19898399-ae77-4fa9-959f-da0d563feeeb">

**Comment by RenzeLou** [comment]
Hi KOU,

Thanks for being interested in our work, and many thanks for proposing this env issue.

I have changed the env setup to use `pip` instead of conda yml files.

Pls use the following pip command (the corresponding [README](https://github.com/RenzeLou/AAAR-1.0?tab=readme-ov-file#environment-setup) file has been updated as well):

```
conda create -n litellm python=3.9
conda activate litellm
pip install -r env_source/requirements.litellm.txt
```

Feel free to open an issue if problems with the environment persist.
